# Config file for automatic testing at travis-ci.org

language: python

# Faster, containerized builds
sudo: false

python:
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

env:
  # Lowest supported IPython version
  - SHELLS="ipython==4.2.0"
  # Latest IPython
  - SHELLS="ipython"
  - SHELLS="ptpython==0.34"

install:
  - pip install -U .
  - pip install invoke pytest scripttest flake8
  - pip install -U "$SHELLS"

script: inv test
